name: Build PrayerTimes Electron

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:  
        os: [macOS-latest,windows-latest]

    steps:
      - name: Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check out Git repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: Install dependencies
        run: |
          yarn install
      
      - name: Build Webpack (Render Thread)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          echo "$GOOGLE_API_KEY"
          yarn run webpack
      
      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn run dist
      
      - name: Cleanup macOS Artifacts
        if: matrix.os == 'macOS-latest'
        run: |
          mkdir artifacts
          mv dist/*.dmg artifacts || true
      - name: Cleanup Win artifacts 
        if: matrix.os == 'windows-latest'
        run: |
          mkdir artifacts
          mv dist/*.exe artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
