name: Build PrayerTimes Electron

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest, windows-latest]

    steps:
      - name: Use Node.js 21.4.0
        uses: actions/setup-node@v1
        with:
          node-version: '21.4.0'

      - name: Checkout Git repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: npm install

      - name: Build Webpack (Render Thread)
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NODE_ENV: production
        run: npm run webpack

      - name: Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist

      - name: Cleanup artifacts
        run: |
          mkdir artifacts
          mv dist/*.dmg artifacts || true
        if: matrix.os == 'macOS-latest' || matrix.os == 'windows-latest'

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.os }}
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}